# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Citizen's Guide to Open Data"
email: geothink.opendata.guide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Citizen’s Guide aims to provide citizens with tools to understand what makes up open data (OD), how it can be used in their communities, and where to find it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://citizens-guide-open-data.github.io/" # the base hostname & protocol for your site
twitter_username: geothinkca
github_username: citizens-guide-open-data

# Build settings
markdown: kramdown
